### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [ankon/attachable-debugger#2]
Hi
The following lines have cryptographic API misuses. <br> File name => agent/src/main/java/nu/borrel/tools/debugger/agent/asm/asm4/commons/SerialVersionUIDAdder.java: Line number => 460: API name => MessageDigest:<BR> File name => agent/src/main/java/nu/borrel/tools/debugger/agent/asm/asm4/commons/SerialVersionUIDAdder.java: Line number => 460: API name => MessageDigest:First parameter (with value "SHA") should be any of {SHA-256, SHA-384, SHA-512}<BR> File name => agent/src/main/java/nu/borrel/tools/debugger/agent/asm/asm4/commons/SerialVersionUIDAdder.java: Line number => 460: API name => MessageDigest:<BR>

**Comment by ankon** [comment]
Closing: Looks like this is some form of misguided "security research", based on looking at similar issues filed in other repositories.
